FROM  golang:1.24 As builder

WORKDIR   /app


COPY go.mod  go.sumn ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM apline:latest

WORKDIR /root/

COPY --from=builder  /app/app .

EXPOSE 8080

CMD ["./app"]
